### ISSUE TITLE
Odd installation behavior

### ISSUE THREAD

**Issue by SoneeJohn** [potionfactory/LetsMove#57] opened 2016-09-09 01:47 UTC
Using the Lets Move Test app I noticed this that I got this alert:

![screen shot 2016-09-08 at 9 39 37 pm](https://cloud.githubusercontent.com/assets/4827301/18372771/031a41b8-760d-11e6-9905-7e089aeab428.png)

I noticed that this line:
`NSArray *userApplicationsDirs = NSSearchPathForDirectoriesInDomains(NSApplicationDirectory, NSUserDomainMask, YES);`

produces an array like similar to this: 
![screen shot 2016-09-08 at 9 39 55 pm](https://cloud.githubusercontent.com/assets/4827301/18372811/4cb80828-760d-11e6-907c-52e3e3b464a0.png)

Passing `NO` instead of `YES` gives you this:

![screen shot 2016-09-08 at 9 40 15 pm](https://cloud.githubusercontent.com/assets/4827301/18372842/718081bc-760d-11e6-94dc-86ee5c3682d8.png)

And therefore, the installing in `/Applications/`... instead of `/Users/username/Applications`

![screen shot 2016-09-08 at 9 40 25 pm](https://cloud.githubusercontent.com/assets/4827301/18372871/a26cff4e-760d-11e6-9b2d-02b27fb6a2aa.png)

I'm guessing this is a mistake or am I'm missing something here?

**Comment by gnachman** [comment] 2016-09-11 19:20
Seems to be intentional. They use ~/Applications if it exists and contains at least one app, otherwise /Applications is used. I guess it's better for multi-user systems.

**Comment by andypotion** [comment] 2016-09-13 01:04
I don't understand why this is a problem.

Is there ever a case where `~/Applications` and `/Users/username/Applications` are different locations on disk?

Right before moving the app, we would need to expand the tilde using another API. Wouldn't that give us `/Users/username/Applications` anyway?

**Comment by SoneeJohn** [comment] 2016-09-13 01:08
@andypotion I meant `/Applications/` my bad.

**Comment by SoneeJohn** [comment] 2016-09-13 01:13
@andypotion What I am saying is that I think it would be better to install in the `/Applications` directory instead of the `/Users/username/Applications` the latter may not be better for multi-user systems as @gnachman pointed out.

**Comment by andypotion** [comment] 2016-09-13 01:15
Yup, the default behavior is to install in `~/Applications` if and only if there exists a `~/Applications` directory and if that directory already contains at least one app.

This is the intended behavior for so I'll close this and the PR.

**Closed by andypotion** 2016-09-13 01:15 UTC
